// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDapuYZ_8cJhXxrNd7V3rbcC1EQmAex7qU',
    appId: '1:953427963506:web:45697c02fbf480a2409ceb',
    messagingSenderId: '953427963506',
    projectId: 'spm-project-cd3d5',
    authDomain: 'spm-project-cd3d5.firebaseapp.com',
    storageBucket: 'spm-project-cd3d5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBniSR2qzPWio9WeDoquPGpWJcfuif71CI',
    appId: '1:953427963506:android:0ef94acc04c68390409ceb',
    messagingSenderId: '953427963506',
    projectId: 'spm-project-cd3d5',
    storageBucket: 'spm-project-cd3d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXCpTtzQ83KaC9mPsA_o5GuLnZ8GdfaB0',
    appId: '1:953427963506:ios:840295d38498a915409ceb',
    messagingSenderId: '953427963506',
    projectId: 'spm-project-cd3d5',
    storageBucket: 'spm-project-cd3d5.appspot.com',
    iosBundleId: 'com.example.ishop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXCpTtzQ83KaC9mPsA_o5GuLnZ8GdfaB0',
    appId: '1:953427963506:ios:b3f24aeabfe30d2c409ceb',
    messagingSenderId: '953427963506',
    projectId: 'spm-project-cd3d5',
    storageBucket: 'spm-project-cd3d5.appspot.com',
    iosBundleId: 'com.example.ishop.RunnerTests',
  );
}
